version: 2

jobs:
  build:
    docker: 
      - image: airtonzanon/php
    working_directory: /app
    steps:
      - checkout
      - run: composer install --no-interaction --optimize-autoloader
      - save_cache:
          key: composer
          paths:
            - ./vendor/
  test:
    docker:
      - image: airtonzanon/php
    working_directory: /app
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer
      - run: ./vendor/bin/phpcs --standard=psr2 -np ./src ./tests
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/infection
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

